---
sidebar: sidebar 
permalink: concept_lic_evaluation.html 
keywords: license, licensing, evaluation, upgrade license 
summary: Wenn Sie ONTAP Select vor der Kaufentscheidung bewerten möchten, können Sie eine Evaluierungslizenz verwenden. Die Evaluierungslizenz ist im ONTAP Select Deploy-Administrationsprogramm enthalten und wird automatisch auf jeden ONTAP Select-Node im Rahmen der Evaluierungsimplementierung angewendet. 
---
= Evaluierungslizenzen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Wenn Sie ONTAP Select vor der Kaufentscheidung bewerten möchten, können Sie eine Evaluierungslizenz verwenden. Die Evaluierungslizenz ist im ONTAP Select Deploy-Administrationsprogramm enthalten und wird automatisch auf jeden ONTAP Select-Node im Rahmen der Evaluierungsimplementierung angewendet.

[NOTE]
====
Um das ONTAP Select Deploy-Verwaltungsprogramm herunterzuladen, benötigen Sie Folgendes:

* Ein registriertes NetApp Support Site Konto Wenn Sie noch kein Konto haben, lesen Sie https://mysupport.netapp.com/site/user/registration["Benutzerregistrierung"^].
*  https://mysupport.netapp.com/site/downloads/evaluation/ontap-select["Akzeptieren Sie die Endbenutzer-Lizenzvereinbarung"^]Für eine ONTAP Select-Implementierung mit einer Evaluierungslizenz.


====


== Merkmale der Lizenzierung

Die ONTAP Select Evaluierungslizenz weist folgende Merkmale auf:

* Es ist keine Produktionslizenz mit Storage-Kapazität erforderlich
* Die Seriennummer des Nodes besteht aus zwanzig Ziffern und wird von ONTAP Select Deploy automatisch generiert
+
(Sie erwerben sie nicht direkt von NetApp.)

* Der von der Lizenz bereitgestellte Evaluierungszeitraum kann bis zu 90 Tage dauern
* Der von jedem Node zugewiesene maximale Storage entspricht der jeweils vorhandenen Produktionslizenz




== Upgrade auf eine Produktionslizenz

Sie können ein ONTAP Select Evaluation Cluster auf eine Produktionslizenz aktualisieren. Sie sollten die folgenden Einschränkungen beachten:

* Sie müssen das Dienstprogramm „Deploy Administration“ verwenden, um die Lizenzaktualisierung durchzuführen
* Es kann eine Lizenz für Kapazitäts-Tiers verwendet werden, jedoch wird die Lizenzierung von Kapazitäts-Pools nicht unterstützt
* Jeder Node muss über ausreichend Storage verfügen, um die erforderliche Mindestmenge für eine Produktionslizenz basierend auf der Cluster-Größe zu unterstützen


Weitere Informationen finden Sie unter link:task_adm_licenses.html["Umwandeln einer Evaluierungslizenz in eine Produktionslizenz"] .

.Verwandte Informationen
* link:concept_lic_production.html["Erfahren Sie mehr über Lizenzen für Produktionsbereitstellungen"]

