---
sidebar: sidebar 
permalink: task_cli_upgrade_deploy.html 
keywords: administer, administering, cli, deploy, upgrade deploy 
summary: Sie können ein vorhandenes Deploy Utility Virtual Machine direkt über die Befehlszeilenschnittstelle aktualisieren. 
---
= Aktualisieren einer Deploy-Instanz
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können ein vorhandenes Deploy Utility Virtual Machine direkt über die Befehlszeilenschnittstelle aktualisieren.



== Bevor Sie beginnen

Stellen Sie sicher, dass Deploy während des Upgrades nicht für andere Aufgaben verwendet wird. Sie sollten die aktuellen Versionshinweise einsehen, um Informationen und Einschränkungen zum Upgrade des Deploy-Dienstprogramms zu erhalten.


NOTE: Wenn Sie eine ältere Instanz des ONTAP Select Deploy-Verwaltungsdienstprogramms installiert haben, sollten Sie auf die aktuelle Version aktualisieren. Der ONTAP Select Node und die ONTAP Select Deploy Komponente werden unabhängig voneinander aktualisiert. Weitere Informationen finden Sie unter link:concept_adm_upgrading_nodes.html["Aktualisieren Sie die ONTAP Select-Nodes"^] .



== Laden Sie das Upgrade-Paket herunter

Um den Aktualisierungsprozess zu starten, müssen Sie die entsprechende Upgrade-Datei für die Deploy-virtuelle Maschine von der NetApp Support Site herunterladen. Das Upgrade-Paket ist als einzelne komprimierte Datei formatiert.

.Schritte
. Greifen Sie mit einem Webbrowser auf link:https://mysupport.netapp.com/site/["NetApp Support Site"^] zu und wählen Sie *Downloads* aus dem Menü Downloads.
. Scrollen Sie nach unten und wählen Sie *ONTAP Select Deploy Upgrade* aus.
. Wählen Sie die gewünschte Version des Upgrade-Pakets aus.
. Lesen Sie die Endbenutzer-Lizenzvereinbarung (EULA), und wählen Sie *Accept & Continue* aus.
. Wählen Sie das passende Paket aus und laden Sie es herunter, und beantworten Sie alle Eingabeaufforderungen entsprechend Ihrer Umgebung.




== Laden Sie das Paket auf die virtuelle Maschine Deploy hoch

Nach dem Erwerb des Upgrade-Pakets müssen Sie die Datei auf die Deploy-virtuelle Maschine hochladen.

.Bevor Sie beginnen
Sie müssen die Upgrade-Datei auf Ihrem lokalen Rechner verfügbar haben. Sie müssen außerdem das Passwort für das Administrator-Benutzerkonto haben.

.Über diese Tasks
Diese Aufgabe beschreibt eine Methode zum Hochladen der Datei auf die virtuelle Maschine bereitstellen. Möglicherweise gibt es weitere für Ihre Umgebung geeignetere Optionen.

.Schritte
. Verwenden Sie in einer Befehlsshell auf Ihrer lokalen Workstation das Dienstprogramm scp, um die Image-Datei auf die Deploy-virtuelle Maschine hochzuladen.
+
Beispiel

+
....
scp ONTAPdeploy2.12_upgrade.tar.gz admin@10.228.162.221:/home/admin (provide password when prompted)
....


.Ergebnis
Die Upgrade-Datei wird im Home-Verzeichnis des Admin-Benutzers gespeichert.



== Wenden Sie das Upgrade-Paket an

Nachdem die Upgrade-Datei auf die Deploy-virtuelle Maschine hochgeladen wurde, können Sie das Upgrade anwenden.

.Bevor Sie beginnen
Sie müssen wissen, in welchem Verzeichnis die Upgrade-Datei auf der Deploy Utility-VM abgelegt wurde. Stellen Sie außerdem sicher, dass Deploy während des Upgrades nicht für andere Aufgaben verwendet wird.

.Schritte
. Melden Sie sich in der CLI des Bereitstellungsdienstprogramms mithilfe von SSH mit dem Administratorkonto an.
. Führen Sie das Upgrade mithilfe des entsprechenden Verzeichnispfads und Dateinamens durch:
+
`deploy upgrade -package-path FILEPATH`

+
Beispiel

+
....
deploy upgrade -package-path /home/admin/ONTAPdeploy2.12_upgrade.tar.gz
....


.Nachdem Sie fertig sind
Bevor das Upgrade-Verfahren abgeschlossen ist, werden Sie aufgefordert, eine Sicherung der Deploy-virtuellen Maschinenkonfiguration zu erstellen. Außerdem sollten Sie den Browser-Cache leeren, damit Sie die neu erstellten Deploy-Seiten anzeigen können.
